name = "DiscreteEventsCompanion"
uuid = "fc125f2d-4e97-4021-a65c-62c1b149a5de"
authors = ["Paul Bayer"]
version = "0.3.0"

[deps]
DiscreteEvents = "127e53a7-d08a-4bd9-afb0-daf0d2b65a85"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
